AllEnchants:
    type: data
    Enchants:
      NormalMelee:
      - bane_of_arthropods
      - fire_aspect
      - knockback
      - looting
      - mending
      - vanishing_curse
      - sharpness
      - smite
      - sweeping
      - unbreaking
      Bow:
      - vanishing_curse
      - flame
      - infinity
      - power
      - punch
      - unbreaking
      - mending
      Crossbow:
      - vanishing_curse
      - unbreaking
      - mending
      - multishot
      - piercing
      - quick_charge
      Trident:
      - channeling
      - vanishing_curse
      - impaling
      - loyalty
      - mending
      - riptide
      - unbreaking
      Armor:
      - vanishing_curse
      - binding_curse
      - blast_protection
      - fire_protection
      - projectile_protection
      - protection
      - thorns
      - mending
      - unbreaking
      - frost_walker
      - soul_speed
      - depth_strider
      - aqua_affinity
      - feather_falling
      - respiration
      - swift_sneak
      shovels:
      - wooden
      - stone
      - gold
      - diamond
      - netherite
      pickaxes:
      - wooden
      - stone
      - gold
      - diamond
      - netherite
    Trims:
      Material:
      - AMETHYST
      - COPPER
      - DIAMOND
      - EMERALD
      - GOLD
      - IRON
      - LAPIS
      - NETHERITE
      - QUARTZ
      - REDSTONE
      Pattern:
      - COAST
      - DUNE
      - EYE
      - HOST
      - RAISER
      - RIB
      - SENTRY
      - SHAPER
      - SILENCE
      - SNOUT
      - SPIRE
      - TIDE
      - VEX
      - WARD
      - WAYFINDER
      - WILD
    Abilities:
      Passive:
      - ImmuneFire
      - ImmuneDrowning
      - ImmunePoison
      - ImmuneWither
      - NoFallDamage
      - Totem
      - Sneaky
      - NoKnockback
      - AntiBoatMount
      - ArrowProof
      - ExplosiveShot
      - ExplodeOnDie
      - FastLearner
      - ReinforcementMelee
      - ReinforcementRanged
      - ReinforcementWolves
      - HeavyHitter
      - HighJumper
      - Trapper
      - LifeSteal
      - BlindDamage
      - ShieldBreaker
      - CheatsDeath
      - MiningFatigue
      - FastMiner
      - OverwhelmingWill
      - Terrorize
      - BlockAttack
      - Combo
      - LassoTarget
      - ThrowEnderPearl
      - SmokeBombs
      - ThrowingDaggers
      - FrontalRoar
      - GroundPound
      - LandMines
      - Mounted
      - BadOmen
      - GolemToss
      - DashStrike
    Names:
      First:
      - Abaddon
      - Aelon
      - Afteryn
      - Akara
      - Andon
      - Antimony
      - Armo
      - Bob
      - Branac
      - Bushamp
      - Cobalt
      - Colearias
      - Corypheus
      - Crass
      - Crost
      - Damiel
      - Darik
      - Difosgeno
      - Donesenojax
      - Dorak
      - Drygma
      - Ehel
      - Elares
      - Emovebaris
      - Eran
      - Eulan
      - Evigilo
      - Falastia
      - Froror
      - Ganglo
      - Gorlock
      - Grisse
      - Gygax
      - Hagederd
      - Hix
      - Illos
      - Iregge
      - Jacobson
      - Jarl
      - Jasper
      - Jeffery
      - Jorn
      - Josh
      - Keenu
      - Keppa
      - Krul
      - Lamar
      - LLoren
      - Lygorax
      - Maldonis
      - Malid
      - Matel
      - Meedin
      - Minthara
      - Mobarne
      - Moraxis
      - Naomi
      - Nyx
      - Odann
      - Olga
      - Oxonn
      - Ozark
      - Phylox
      - Pohban
      - Prak
      - Prish
      - Promethean
      - Quid
      - Quo
      - Quol
      - Riney
      - Samuel
      - Sana
      - Stino
      - Sunup
      - Tahnk
      - Tarrask
      - Taryn
      - Terryn
      - Tholix
      - Thoraxis
      - Thyn
      - Uma
      - Urdol
      - Urun
      - Vipen
      - Wislow
      - Worcasp
      - Wren
      - Wrex
      - Xerxes
      - Yamel
      - Yanzu
      - Yuslaw
      - Zamp
      - Zesh
      Last:
      - Bladesong
      - Blood Blender
      - Bloodsucker
      - Bloodtears
      - Boulder-Breaker
      - Deathbringer
      - Eagle-eye
      - from Deep Dark
      - from Hell
      - from Nowhere
      - from the Skies
      - Hammerhead
      - Havoc
      - Human-hater
      - Icesong
      - Ironfist
      - Jaws
      - Kings Pawn
      - Kings-blade
      - Manhunter
      - Manslayer
      - Nightfire
      - No Mercy
      - of The End
      - of The Nether
      - of the Water
      - Outragous
      - Speedster
      - Stronghand
      - the Archaic
      - the Assassin
      - the Banana
      - the Beast
      - the Besieger
      - the Black
      - the Calculated
      - the Catastrophic
      - the Chosen One
      - the Culler
      - the Dangerous
      - the Dark
      - the Destroyer
      - the Disrespectful
      - the Dumb
      - the Enlightened
      - the Forgotten
      - the Great
      - the Greedful
      - the Guardian of Order
      - the Hopeful
      - the Hunter
      - the Hurtful
      - the Idiot
      - the Insane
      - the Intrepid
      - the Joke
      - the Killer
      - the Leader
      - the Loud
      - the Martyr
      - the Nemesis
      - the Nullifier
      - the Outcast
      - the Powerful
      - the Predator
      - the Promised
      - the Razor
      - the Relentless
      - the Rival
      - the Smart
      - the Strong
      - the Suffering
      - the Terrible
      - the Thief
      - the Throgler
      - the Unknown
      - the Unseen
      - the Weak
      - the Wise
      - the World Ender
      - Twig Legs
      - Who Cries
      - Who Hurts
      - Who Sees
      - Who Succeeds
      - Who Walks
    Quotes:
      Digging:
      - Placing blocks won't help!
      - What do you think you're doing?
      - Hiding won't help!
      - Stop hiding <player.name>!
      - Trying to cover yourself are you?
      - I'll break every block I can to get to you!
      - I'll break any block to find you!
      - Do you really think you are that smart?
      - I see you!
      - I can see you <player.name>!
      - I'm getting closer to you!
      - Just what are you trying to do?
      - Burrowing away from me are you?
      - <player.name>, stop hiding!
      - I'm smarter than that <player.name>!
      - I can still hear you!
      - I'm getting closer!
      - Behind or beneath blocks, I'll get you!
      - Going underground won't help!
      - Going behind blocks isn't going to work!
      - I know you're in there <player.name>!
      - Unlucky for you, I can dig!
      - My hands won't tire trying to find you!
      - I know you're down there, somewhere!
      - I know you are there!
      - Hiding behind blocks?!?
      - Coward!
      - Fight me like a true warrior, <player.name>!
      - Get away from there!
      - Quit being a coward!
      - Heh, there's no way to escape me.
      - I hate it when you do this...
      - Stop stalling!
      - I know where you are <player.name>!
      - I can hear you!
      - So you are over there eh?
      - I'm going to get you!
      - I hear you... over there!
      - Just so you know, I know exactly where you are.
      - I will dig forever to get to you!
      - I will keep coming for you!
      - Digging isn't going to work!
      - Hiding can only do so much!
      - You can't hide, nor can you run.
      - Ah, there you are <player.name>.
      HighUp:
      - Get down from there!
      - Hey <player.name>, get down here!
      - How's this for a change?
      - So you think you can pillar up?
      - Do you think I'm just stupid?
      - You're smart, but I'm smarter!
      - Eat this!
      - Take my dagger!
      - Going up are you <player.name>?
      - Stop camping!
      - Don't you stay up there!
      - Get down!
      - I can shoot stuff you know.
      - Take this dagger <player.name>!
      - Here's hoping you stumble and fall!
      - Stumble and fall!
      - I will knock you down!
      - Fall down <player.name>!
      - Jump off a cliff will you!
      - I'll knock you off!
      - You can't stay up there forever!
      - Take my barrage of arrows then!
      - Oh no you don't!
      - Come back down here!
      - I'll keep shooting you!
      - My blade can't get you, but this can!
      - Pillaring up isn't going to work <player.name>!
      - I'll keep throwing daggers then!
      - These daggers have been weighing me down anyhow.
      - <player.name>, going up can only help so much!
      - I'm not letting you escape.
      - You'll be swatted off like a fly!
      - The bigger they are, the harder they fall!
      - You're so bad that you need to use the high ground? Pathetic.
      - The high ground makes no difference!
      - Being up there will only make things worse.
      - Stop resorting to cheap tactics!
      - <player.name>, you make this a pain for me!
      - Watch what happens next.
      - Oh please, how is pillaring up going to help?
      - Take this to the knee!
      - Get off from up there!
      - Get away from there!
      - This will slap you away!
      - Come right down to papa, <player.name>!
      - I think you've enjoyed your view from up there for long enough.
      - Zoning me out? Not on my watch!
      - Tremble and fall down!
      - Go on, tower up, and I'll do my worst!
      Adapted:
      - I've seen you do that before!
      - Not gonna work!
      - Saw that coming!
      - I saw that coming!
      - Nuh-uh!
      - Nope!
      - Your moves are boring me!
      - Your fighting style is boring!
      - So predictable are you <player.name>?!?
      - I've adapted to that!
      - Learn something new!
      - Stop spamming!
      - Quit spamming <player.name>!
      - Is that all you know?
      - Is that the only move you know?
      - You haven't learned anything!
      - I see through your attacks!
      - I adapt to anything!
      - You didn't think I would adapt?
      - Stop throwing the same moves!
      - So repetitive!
      - You are so repetitive <player.name>!
      - I knew you were going to do that!
      - That's the only move you depend on?
      - Just like you I learn!
      - Same old, same old!
      - Adapted to that already!
      - Go on, keep spamming that! See how it goes!
      - Oh <player.name>, when will you change?
      - Why did you think that would work?
      - I had foresight on that.
      - Just stop using that move!
      - Why do you keep thinking that will work?
      - Another repeated move, another day.
      - I guess that's all you know.
      - Hey <player.name>, go back to school!
      - I saw that cheap trick coming again!
      - Wasn't going to work this time!
      - Have you ever learned?
      - That wasn't going to work!
      - That really is all you can do!
      - Happened once, shame on me. Happens twice, shame on you!
      - Yeah, uh, no.
      - Wasn't going to work again, <player.name>!
      Fighting:
      - HA ha weakling!
      - I'll make your heaven harder than hell.
      - Is that the best you got?
      - I can do this all day, any day!
      - What do you think of this?
      - Here is my next move!
      - Die already!
      - I'll be sure to enjoy killing you.
      - I am the better fighter than you!
      - This is your end, <player.name>.
      - Enjoy these last moments!
      - Eat it!
      - Let's endure.
      - Only one of us is going to live!
      - This one will kill you <player.name>.
      - This goes to your face!
      - You may hit hard, but I hit harder!
      - This fight will be legendary.
      - <player.name>, we need to end this now.
      - 2 go in for battle, only 1 comes out to live.
      - I dedicate this attack to you, <player.name>.
      - I'm not going down today!
      - This is gonna hurt!
      - You're the butter, and I'm the knife!
      - HI-YAH!
      - Let's see if you can endure this pain.
      - It's not looking good.
      - Here's a question: Are you dumb or stupid?
      - You fight like a little kid.
      - I've met toddlers stronger than you <player.name>!
      - Soon, your insides will be outside!
      - Only the strongest one will win.
      - May the best soldier win.
      - Are you supposed to be a threat?
      - Oh look at me, I'm sooooo scared of <player.name>!
      - Now you die!
      - You'll die at my hand!
      - Just make it easy for me and kill yourself!
      - A true warrior never backs off from a fight.
      - Do me a favor, and go commit suicide!
      - Stop making this hard for me!
      - You will never escape me, <player.name>!
      - I want you to bleed.
      - I want you to suffer.
      - You really think you can kill me?
      - You will die, right now!
      - This will be a 1 way slaughter: against you!
      - You have no chance.
      - There's no chance for you <player.name>!
      - Give it up, you're no good.
      - This next hit may kill you.
      - Are you trying your hardest?
      - This fight is a total joke.
      - And take this!
      - As long as I am still standing, I will fight!
      - Nothing can stop me!
      - I am unstoppable.
      - Do you have any last words?
      - I am superior!
      - I've got you where I want you!
      - I'll do my best, while you do your worst!
