AllEnchants:
    type: data
    Enchants:
      NormalMelee:
      - bane_of_arthropods
      - fire_aspect
      - knockback
      - looting
      - mending
      - vanishing_curse
      - sharpness
      - smite
      - sweeping
      - unbreaking
      Bow:
      - vanishing_curse
      - flame
      - infinity
      - power
      - punch
      - unbreaking
      - mending
      Crossbow:
      - vanishing_curse
      - unbreaking
      - mending
      - multishot
      - piercing
      - quick_charge
      Trident:
      - channeling
      - vanishing_curse
      - impaling
      - loyalty
      - mending
      - riptide
      - unbreaking
      Armor:
      - vanishing_curse
      - binding_curse
      - blast_protection
      - fire_protection
      - projectile_protection
      - protection
      - thorns
      - mending
      - unbreaking
      - frost_walker
      - soul_speed
      - depth_strider
      - aqua_affinity
      - feather_falling
      - respiration
      - swift_sneak
      shovels:
      - wooden
      - stone
      - gold
      - diamond
      - netherite
      pickaxes:
      - wooden
      - stone
      - gold
      - diamond
      - netherite
    Trims:
      Material:
      - AMETHYST
      - COPPER
      - DIAMOND
      - EMERALD
      - GOLD
      - IRON
      - LAPIS
      - NETHERITE
      - QUARTZ
      - REDSTONE
      Pattern:
      - COAST
      - DUNE
      - EYE
      - HOST
      - RAISER
      - RIB
      - SENTRY
      - SHAPER
      - SILENCE
      - SNOUT
      - SPIRE
      - TIDE
      - VEX
      - WARD
      - WAYFINDER
      - WILD
    Abilities:
      Passive:
      - ImmuneFire
      - ImmuneDrowning
      - NoFallDamage
      - Totem
      - Sneaky
      - NoKnockback
      - AntiBoatMount
      - ArrowProof
      - ExplosiveShot
      - ExplodeOnDie
      - FastLearner
      - ReinforcementMelee
      - ReinforcementRanged
      - ReinforcementWolves
      - HeavyHitter
      - HighJumper
      - Trapper
      - LifeSteal
      - BlindDamage
      - ShieldBreaker
      - CheatsDeath
      - MiningFatigue
      - FastMiner
      - OverwhelmingWill
      - Terrorize
      - BlockAttack
      - Combo
      - LassoTarget
      - ThrowEnderPearl
      - SmokeBombs
      - ThrowingDaggers
      - FrontalRoar
      - GroundPound
      - LandMines
      - Mounted
      - BadOmen
    Names:
      First:
      - Bob
      - Armo
      - Keenu
      - Jorn
      - Eran
      - Illos
      - Akara
      - Zesh
      - Crass
      - Hix
      - Jarl
      - Urun
      - Damiel
      - Worcasp
      - Prish
      - LLoren
      - Froror
      - Sunup
      - Dorak
      - Cobalt
      - Branac
      - Yuslaw
      - Wislow
      - Jasper
      - Gorlock
      - Jeffery
      - Sana
      - Ozark
      - Xerxes
      - Riney
      - Keppa
      - Prak
      Last:
      - the Throgler
      - Kings Pawn
      - the Destroyer
      - the Idiot
      - the Dumb
      - the Smart
      - the Wise
      - the Powerful
      - the Strong
      - the Weak
      - Manslayer
      - Manhunter
      - Kings-blade
      - the Disrespectful
      - the Assassin
      - the Hunter
      - the Banana
      - Eagle-eye
      - Bloodsucker
      - the Nemesis
      - from Nowhere
      - of The End
      - of The Nether
      - Human-hater
      - the Dangerous
      - No Mercy
      - the Relentless
      - the Beast
      - Speedster
      - Outragous
      - from Deep Dark
      - the Insane
      - the Hurtful
      - the Killer
      - from Hell
      - Jaws
    Quotes:
      Digging:
      - Placing blocks won't help!
      - What do you think you're doing?
      - Hiding won't help!
      - Stop hiding <player.name>!
      - Trying to cover yourself are you?
      - I'll break every block I can to get to you!
      - I'll break any block to find you!
      - Do you really think you are that smart?
      - I see you!
      - I can see you <player.name>!
      - I'm getting closer to you!
      - Just what are you trying to do?
      - Burrowing away from me are you?
      - <player.name>, stop hiding!
      - I'm smarter than that <player.name>!
      - I can still hear you!
      - I'm getting closer!
      - Behind or beneath blocks, I'll get you!
      - Going underground won't help!
      - Going behind blocks isn't going to work!
      - I know you're in there <player.name>!
      - Unlucky for you, I can dig!
      - My hands won't tire trying to find you!
      - I know you're down there, somewhere!
      - I know you are there!
      - Hiding behind blocks?!?
      - Coward!
      - Fight me like a true warrior, <player.name>!
      HighUp:
      - Get down from there!
      - Hey <player.name>, get down here!
      - How's this for a change?
      - So you think you can pillar up?
      - Do you think I'm just stupid?
      - You're smart, but I'm smarter!
      - Eat this!
      - Take my dagger!
      - Going up are you <player.name>?
      - Stop camping!
      - Don't you stay up there!
      - Get down!
      - I can shoot stuff you know.
      - Take this dagger <player.name>!
      - Here's hoping you stumble and fall!
      - Stumble and fall!
      - I will knock you down!
      - Fall down <player.name>!
      - Jump off a cliff will you!
      - I'll knock you off!
      - You can't stay up there forever!
      - Take my barrage of arrows then!
      - Oh no you don't!
      - Come back down here!
      - I'll keep shooting you!
      - My blade can't get you, but this can!
      - Pillaring up isn't going to work <player.name>!
      - I'll keep throwing daggers then!
      - These daggers have been weighing me down anyhow.
      - <player.name>, going up can only help so much!
      Adapted:
      - I've seen you do that before!
      - Not gonna work!
      - Saw that coming!
      - I saw that coming!
      - Nuh-uh!
      - Nope!
      - Your moves are boring me!
      - Your fighting style is boring!
      - So predictable are you <player.name>?!?
      - I've adapted to that!
      - Learn something new!
      - Stop spamming!
      - Quit spamming <player.name>!
      - Is that all you know?
      - Is that the only move you know?
      - You haven't learned anything!
      - I see through your attacks!
      - I adapt to anything!
      - You didn't think I would adapt?
      - Stop throwing the same moves!
      - So repetitive!
      - You are so repetitive <player.name>!
      - I knew you were going to do that!
      - That's the only move you depend on?
      - Just like you I learn!
      - Same old, same old!
      - Adapted to that already!
      - Go on, keep spamming that! See how it goes!
      - Oh <player.name>, when will you change?
      Fighting:
      - HA ha weakling!
      - I'll make your heaven harder than hell.
      - Is that the best you got?
      - I can do this all day, any day!
      - What do you think of this?
      - Here is my next move!
      - Die already!
      - I'll be sure to enjoy killing you.
      - I am the better fighter than you!
      - This is your end, <player.name>.
      - Enjoy these last moments!
      - Eat it!
      - Let's endure.
      - Only one of us is going to live!
      - This one will kill you <player.name>.
      - This goes to your face!
      - You may hit hard, but I hit harder!
      - This fight will be legendary.
      - <player.name>, we need to end this now.
      - 2 go in for battle, only 1 comes out to live.
      - I dedicate this attack to you, <player.name>.
      - I'm not going down today!
      - This is gonna hurt!
      - You're the butter, and I'm the knife!
      - HI-YAH!
      - Let's see if you can endure this pain.
      - It's not looking good.
      - Here's a question: Are you dumb or stupid?
      - You fight like a little kid.
      - I've met toddlers stronger than you <player.name>!
      - Soon, your insides will be outside!
      - Only the strongest one will win.
      - May the best soldier win.
      - Are you supposed to be a threat?
      - Oh look at me, I'm sooooo scared of <player.name>!
      - Now you die!
